import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import '../css/styles.css'
import './react.css'

const money = value => value.toLocaleString('en-US', { style: 'currency', currency: 'USD' })

function Header() {
  return <nav className="navbar"><div><div className="brand">Trade<span>Guard</span></div><div className="brand-subtitle">Trade Order & Risk Management</div></div><div className="nav-right"><div className="market-status"><span className="status-dot" />Market Open</div><div className="nav-links"><NavLink to="/dashboard">Dashboard</NavLink><NavLink to="/orders">Orders</NavLink><NavLink to="/login">Logout</NavLink></div></div></nav>
}

function Auth({ register = false }) {
  const navigate = useNavigate()
  const submit = event => { event.preventDefault(); if (register) window.alert('Account created successfully.'); navigate(register ? '/login' : '/dashboard') }
  return <main className="auth-body"><div className="auth-card"><h1>{register ? 'Create Account' : 'TradeGuard'}</h1>{!register && <p className="subtitle">Trade Order & Portfolio Management</p>}<form onSubmit={submit}>{register && <><label htmlFor="email">Email</label><input id="email" type="email" required /></>}<label htmlFor="username">Username</label><input id="username" required /><label htmlFor="password">Password</label><input id="password" type="password" required /><button className="primary-btn" type="submit">{register ? 'Register' : 'Login'}</button></form><p className="auth-link">{register ? 'Already have an account?' : "Don't have an account?"} <NavLink to={register ? '/login' : '/register'}>{register ? 'Login' : 'Register'}</NavLink></p></div></main>
}

const holdings = [['AAPL',20,'$180.20','$210.00','$4,200.00','+16.54%','▁▂▃▄▅▇','positive'],['MSFT',10,'$410.10','$422.50','$4,225.00','+3.02%','▂▂▃▄▆▇','positive'],['NVDA',5,'$175.00','$184.08','$920.40','+5.19%','▁▃▂▄▅▇','positive'],['TSLA',12,'$352.00','$340.00','$4,080.00','-3.41%','▇▆▅▄▂▁','negative']]
function PanelHeader({ title, subtitle }) { return <div className="panel-header"><div><h2>{title}</h2><p>{subtitle}</p></div></div> }

function Dashboard() {
  const metrics = [['Cash Available','$25,000.00','42% of account value'],['Pending Orders','3','Awaiting review'],['Largest Position','AAPL','34% portfolio allocation'],["Today's P/L",'+$842.12','+1.44%']]
  const insights = [['warning','!','Position concentration','AAPL represents 34% of portfolio value.'],['safe','✓','Cash reserve healthy','42% of account value remains available.'],['safe','✓','No active compliance flags','No current orders require escalation.']]
  const activity = [['buy-dot','BUY AAPL','20 shares · Pending','2:41 PM'],['sell-dot','SELL MSFT','5 shares · Approved','1:18 PM'],['neutral-dot','Account Login','Successful authentication','10:03 AM']]
  return <><Header /><main className="container"><div className="page-heading"><p className="eyebrow">OVERVIEW</p><h1>Portfolio Dashboard</h1><p className="muted">Monitor positions, risk, and trading activity.</p></div><div className="hero-grid"><section className="portfolio-hero"><p className="card-label">Total Account Value</p><h2>$59,345.40</h2><div className="positive hero-change">+$842.12 (+1.44%) today</div><div className="hero-stats"><div><span>Portfolio</span><strong>$34,345.40</strong></div><div><span>Cash</span><strong>$25,000.00</strong></div></div></section><section className="risk-card"><div className="risk-header"><p className="card-label">Portfolio Risk</p><span className="risk-pill">MODERATE</span></div><h2>62</h2><p className="muted">Risk score out of 100</p><div className="risk-bar"><div className="risk-fill" /></div><div className="risk-scale"><span>Low</span><span>High</span></div></section></div><div className="metric-grid">{metrics.map((x,i)=><div className="metric-card" key={x[0]}><span>{x[0]}</span><strong className={i===3?'positive':''}>{x[1]}</strong><small className={i===3?'positive':''}>{x[2]}</small></div>)}</div><div className="trade-actions"><NavLink to="/buy" className="buy-btn">+ Buy Stock</NavLink><NavLink to="/sell" className="sell-btn">− Sell Stock</NavLink></div><section className="panel"><PanelHeader title="Current Holdings" subtitle="Live portfolio positions" /><div className="table-wrapper"><table><thead><tr>{['Ticker','Quantity','Avg Price','Market Price','Value','Return','Trend'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{holdings.map(h=><tr key={h[0]}><td><div className="ticker-cell"><div className="ticker-logo">{h[0][0]}</div><strong>{h[0]}</strong></div></td>{h.slice(1,5).map((v,i)=><td key={i}>{v}</td>)}<td className={h[7]}>{h[5]}</td><td className={`sparkline ${h[7]}`}>{h[6]}</td></tr>)}</tbody></table></div></section><div className="bottom-grid"><section className="panel"><PanelHeader title="Risk Insights" subtitle="Automated portfolio checks" />{insights.map(x=><div className={`insight ${x[0]}`} key={x[2]}><div className="insight-icon">{x[1]}</div><div><strong>{x[2]}</strong><p>{x[3]}</p></div></div>)}</section><section className="panel"><PanelHeader title="Recent Activity" subtitle="Latest account events" />{activity.map(x=><div className="activity" key={x[1]}><div className={`activity-dot ${x[0]}`} /><div><strong>{x[1]}</strong><span>{x[2]}</span></div><small>{x[3]}</small></div>)}</section></div></main></>
}

const initialOrders = [['#1048','AAPL','BUY',20,'$210.00','APPROVED','2:15 PM'],['#1049','AMZN','BUY',5,'$230.00','PENDING','2:32 PM'],['#1047','MSFT','SELL',5,'$422.50','APPROVED','1:18 PM'],['#1046','TSLA','BUY',50,'$340.00','FLAGGED','12:44 PM'],['#1045','NVDA','BUY',100,'$184.08','REJECTED','11:57 AM']]
function Orders() {
  const [orders,setOrders] = useState(initialOrders)
  const cancel = id => { if (window.confirm('Are you sure you want to cancel this pending order?')) setOrders(rows=>rows.map(row=>row[0]===id ? [...row.slice(0,5),'CANCELLED',row[6]] : row)) }
  return <><Header/><main className="container"><div className="page-heading order-heading"><div><p className="eyebrow">ACTIVITY</p><h1>Order History</h1><p className="muted">Review and manage trade orders.</p></div><div className="order-actions"><NavLink to="/buy" className="buy-btn">+ Buy</NavLink><NavLink to="/sell" className="sell-btn">− Sell</NavLink></div></div><div className="order-summary-grid">{[['All Orders','14',''],['Pending','3','warning-text'],['Approved','8','positive'],['Rejected / Flagged','3','negative']].map(x=><div className="order-summary" key={x[0]}><span>{x[0]}</span><strong className={x[2]}>{x[1]}</strong></div>)}</div><section className="panel"><PanelHeader title="Trade Orders" subtitle="Most recent activity first"/><div className="table-wrapper"><table><thead><tr>{['Order','Ticker','Side','Quantity','Price','Status','Submitted','Action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o[0]}><td>{o[0]}</td><td><strong>{o[1]}</strong></td><td><span className={`side-label ${o[2].toLowerCase()}-label`}>{o[2]}</span></td><td>{o[3]}</td><td>{o[4]}</td><td><span className={`status ${o[5].toLowerCase()}`}>{o[5]}</span></td><td>{o[6]}</td><td>{o[5]==='PENDING'?<button className="cancel-btn" onClick={()=>cancel(o[0])}>Cancel</button>:<span className="muted">—</span>}</td></tr>)}</tbody></table></div></section></main></>
}

const positions = { AAPL:{price:210,max:20}, MSFT:{price:422.5,max:10}, NVDA:{price:184.08,max:5} }
function Trade({ side }) {
  const isBuy=side==='buy', navigate=useNavigate(), [ticker,setTicker]=useState('AAPL'), [quantity,setQuantity]=useState(isBuy?10:5), position=positions[ticker], price=isBuy?210:position.price, max=isBuy?Infinity:position.max
  const submit=()=>{ const qty=Number(quantity); if(!Number.isInteger(qty)||qty<=0) return window.alert('Enter a valid quantity.'); if(qty>max) return window.alert(`You only own ${max} shares of ${ticker}.`); if(window.confirm(`Submit ${side.toUpperCase()} order for ${qty} shares of ${ticker}?`)){window.alert(`${isBuy?'Buy':'Sell'} order submitted. Status: Pending`);navigate('/orders')} }
  const checks=isBuy?['Sufficient buying power','Order within position limit']:['Sufficient holdings','Valid quantity','Concentration decreases']
  return <><Header/><main className="container trade-page"><NavLink className="back-link" to="/dashboard">← Back to dashboard</NavLink><div className="trade-page-header"><div><p className="eyebrow">NEW ORDER</p><h1>{isBuy?'Buy':'Sell'} Stock</h1><p className="muted">{isBuy?'Create a new purchase order.':'Sell an existing portfolio position.'}</p></div><span className={`side-pill ${side}-side`}>{side.toUpperCase()}</span></div><div className="trade-layout"><section className="panel trade-form"><div className="form-section"><label htmlFor="ticker">{isBuy?'Stock Symbol':'Select Holding'}</label>{isBuy?<input id="ticker" value="AAPL" readOnly/>:<select id="ticker" value={ticker} onChange={e=>setTicker(e.target.value)}>{Object.entries(positions).map(([t,p])=><option key={t} value={t}>{t} — {p.max} shares</option>)}</select>}{isBuy&&<div className="ticker-result"><div><strong>AAPL</strong><span>Apple Inc.</span></div><div className="quote">$210.00</div></div>}</div>{!isBuy&&<div className="ticker-result"><div><strong>{ticker}</strong><span>Current market price</span></div><div className="quote">{money(price)}</div></div>}<div className="form-section"><label htmlFor="quantity">Quantity</label><input id="quantity" type="number" min="1" max={isBuy?undefined:max} value={quantity} onChange={e=>setQuantity(e.target.value)}/>{!isBuy&&<small>{max} shares available</small>}</div><div className="estimate-card">{isBuy&&<div><span>Market Price</span><strong>$210.00</strong></div>}<div><span>Estimated {isBuy?'Cost':'Proceeds'}</span><strong>{money(price*(Number(quantity)||0))}</strong></div></div><button className={`${side}-btn full-width`} onClick={submit}>Review {isBuy?'Buy':'Sell'} Order</button></section><aside className="panel trade-preview"><PanelHeader title="TradeGuard Check" subtitle={isBuy?'Pre-trade risk analysis':'Position impact analysis'}/><div className="preview-section"><span>{isBuy?'Portfolio':'Position'} Impact</span><div className="impact-row"><span>{isBuy?'AAPL Before':'Current Shares'}</span><strong>{isBuy?'27%':max}</strong></div><div className="impact-row"><span>{isBuy?'AAPL After':'Shares After'}</span><strong>{isBuy?'34%':Math.max(0,max-(Number(quantity)||0))}</strong></div></div><div className="preview-section"><span>Risk Checks</span>{checks.map(x=><div className="check-row safe-text" key={x}>✓ {x}</div>)}{isBuy&&<div className="check-row warning-text">⚠ Concentration increasing</div>}</div><div className="risk-summary"><span>Estimated Risk</span><strong>{isBuy?'MODERATE':'LOW'}</strong></div></aside></div></main></>
}

function App(){return <Routes><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/orders" element={<Orders/>}/><Route path="/buy" element={<Trade side="buy"/>}/><Route path="/sell" element={<Trade side="sell"/>}/><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)
